### ISSUE TITLE
how to change slider length

### ISSUE THREAD

**Issue by saikiranoptisol** [ptomasroos/react-native-multi-slider#102]
everything in this component works fine for me. But i want to know how to change slider length. becuase if i give static lenght like 200 or 300 it may look small or else big in bigger and smaller devices. 
Is there any way to change the slider length

**Comment by ptomasroos** [comment]
Can you please share you solution so other can get help from existing issues?

**Comment by ptomasroos** [comment]
Thanks @saikiranoptisol !
