### ISSUE TITLE
Error on installation

### ISSUE THREAD

**Issue by spyshower** [ptomasroos/react-native-multi-slider#104]
<img width="338" alt="screenshot 2018-12-14 at 18 58 09" src="https://user-images.githubusercontent.com/7046283/50016574-3f98e580-ffd2-11e8-9c36-199c937cccb8.png">

The import line throws this error. I have created so many threads about bugs and errors these days that I honestly can't type another sentence of explaining an error. The image should be enough.

**Comment by spyshower** [comment]
"react-native-multi-slider": "^0.3.6"

**Comment by ptomasroos** [comment]
From the readme

$ npm install --save @ptomasroos/react-native-multi-slider

You are reporting someone else’s error here

**Comment by spyshower** [comment]
Well I originally installed it that way but got this error: 

Unable to resolve "react-native-multi-slider" from "src/components/Screens/Encounters.js"

The example project contains this:
`import MultiSlider from 'react-native-multi-slider';`

instead of
`
import MultiSlider from '@ptomasroos/react-native-multi-slider';`

Anyway thanks a lot for the quick help @ptomasroos . While we are here, is there a way to display the value of the marker about the marker?

**Comment by ptomasroos** [comment]
Look at the examples in the repo. 

Yes the idea was to republish it but we never agreed on the package name. Will fix during Christmas

**Comment by spyshower** [comment]
I mean directly above the marker, so when the marker is moved the value gets moved too.

**Comment by ptomasroos** [comment]
No there is no such thing in the slider it self
