### ISSUE TITLE
add typescript types

### ISSUE THREAD

**Issue by sibelius** [ptomasroos/react-native-multi-slider#108]
Everybody is moving to typescript

it would be cool to have .d.ts for this package

**Comment by ptomasroos** [comment]
Would be great indeed.

**Comment by halbano** [comment]
npm install --save @types/ptomasroos__react-native-multi-slider

Does that definition makes sense?

**Comment by henrikra** [comment]
I have succesfully add types with `npm install --save @types/ptomasroos__react-native-multi-slider` so this ticket can be closed!
