### ISSUE TITLE
Android(bug):Does not work with Navigator gestures

### ISSUE THREAD

**Issue by AnyGong** [ptomasroos/react-native-multi-slider#11]
When Navigator gestures are turned on the gestures take over and the and instead of the slider moving the screen gets dragged to the previous/next scene.

` "@ptomasroos/react-native-multi-slider": "0.0.6"`,

` "react": "15.4.1"`,

` "react-native": "0.39.0",`

**Comment by ptomasroos** [comment]
Interesting. Have you looked into any more?

**Comment by ptomasroos** [comment]
This is sadly a issue existing in the main repo without a clear solution to it https://github.com/facebook/react-native/issues/1046#issuecomment-269449984
