### ISSUE TITLE
Failed to load bundle

### ISSUE THREAD

**Issue by motogod** [ptomasroos/react-native-multi-slider#118]
I have searched [existing issues](https://github.com/ptomasroos/react-native-multi-slider/issues)
I am using the [latest multi slider version](https://www.npmjs.com/package/@ptomasroos/react-native-multi-slider)

## Steps to Reproduce

    1. npm install --save @ptomasroos/react-native-multi-slider
    2. just `import MultiSlider from '@ptomasroos/react-native-multi-slider';` in file.
    3. `react-native run-ios` will show the error on terminal

`error: bundling failed: Error: While trying to resolve module `@ptomasroos/react-native-multi-slider` from file `/Users/motogod19/MyWork/MovieToGo/src/components/More/SearchMovieTimeScreen.js`, the package `/Users/motogod19/MyWork/MovieToGo/node_modules/@ptomasroos/react-native-multi-slider/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`/Users/motogod19/MyWork/MovieToGo/node_modules/@ptomasroos/react-native-multi-slider/MultiSlider.js`. Indeed, none of these files exist:`

  It should be compile when type `react-native run-ios`

**Comment by nphucuong** [comment]
I get the same error ..

**Comment by nphucuong** [comment]
Solved.

`import MultiSlider from '@ptomasroos/react-native-multi-slider'`
