### ISSUE TITLE
Slider callback not working

### ISSUE THREAD

**Issue by MikeDabrowski** [ptomasroos/react-native-multi-slider#12]
Callback value is not updating when sliding bar. It can be seen also on example gif. 

Edit1: typos in
sliderOneValuesChangeStart
sliderOneValuesChange
sliderOneValuesChangeFinish
- first letter was capital. Fixing this causes:
"undefined is not a function (evaluating 'this.setState({sliderOneChanging:true})')

**Comment by MikeDabrowski** [comment]
using  `= () => {` solves the issue. My mistake.

**Comment by ptomasroos** [comment]
👍
