### ISSUE TITLE
Can not install with current 2.0.0 version

### ISSUE THREAD

**Issue by technicalopt** [ptomasroos/react-native-multi-slider#129]
Hi pro,

Did you register released 2.0.0 version to install by command: 
 
npm install --save @ptomasroos/react-native-multi-slider

It always install 1.0.0 version. I tried with this:
npm install --save @ptomasroos/react-native-multi-slider@2.0.0

But no matching version found.

**Comment by ptomasroos** [comment]
Yes sorry it hasn't been released yet. Will publish soon
