### ISSUE TITLE
Question: Does this work with expo client?

### ISSUE THREAD

**Issue by cmacdonnacha** [ptomasroos/react-native-multi-slider#131]
Just a quick question, does this work with expo client or does it have to be ejected?

**Comment by ptomasroos** [comment]
Yes this works with expo since there are no native dependencies

**Comment by cmacdonnacha** [comment]
Great thanks

**Comment by antonigiske** [comment]
I can't seem to make this work on web. Is there anything in the works for making it compatible with web?

**Comment by Abdulraheem42** [comment]
How to work this dependencies react-native-multi-slider with react native expo? but i use This is not working.
