### ISSUE TITLE
Track bug

### ISSUE THREAD

**Issue by jlgfmhldf** [ptomasroos/react-native-multi-slider#135]
- [x] I have searched [existing issues](https://github.com/ptomasroos/react-native-multi-slider/issues)
- [ ] I am using the [latest multi slider version](https://www.npmjs.com/package/@ptomasroos/react-native-multi-slider)

Hi, I am using latest version from github repository. When i running example i get it https://monosnap.com/file/pFmIl4yUBBQvMtLszi4d6IxzByO129

**Comment by myckhel** [comment]
temporary solution

copied converters.js, DefaultLable.js, DefaultMarker.js, MultiSlider.js from https://github.com/ptomasroos/react-native-multi-slider/tree/410221bd455783922ed150b9386cbfd41880e869 to node_modules/react-native-multi-slider

**Comment by robwalkerco** [comment]
Has anyone worked out whats causing this?

@myckhel I've tried installing the commit in your comment, as well as the current master, and I'm still getting the track bug :(

**Comment by myckhel** [comment]
Did you npm install or yarn add https://github.com/ptomasroos/react-native-multi-slider#410221bd455783922ed150b9386cbfd41880e869

Then i hope it wasn't installed

Try to confirm if the commit was installed by checking the package.json

If you would see the commit id

Im very sure with that commit id you shouldn't experience that bug
Because thats what im using uptill now while im waiting for latest update.

**Comment by robwalkerco** [comment]
@myckhel Thanks for your reply. I guess I must have still been pulling in the wrong commit.
Anyway, I've opened a PR with (what I think) is a proper fix.

You can install it now using `ptomasroos/react-native-multi-slider#139/head` in your package.json file if you want to try it out. (I would appreciate a comment on #139 if it works for you ;) )

**Comment by robwalkerco** [comment]
Strange, that method for installing the PR branch doesn't seem to be working for on with npm.
This works though - `robwalkerco/react-native-multi-slider#robwalkerco-patch-1`

**Comment by myckhel** [comment]
Oh great.

Thanks for taking your time to make a PR.
