### ISSUE TITLE
componentWillMount is deprecated warning

### ISSUE THREAD

**Issue by Under-Warz** [ptomasroos/react-native-multi-slider#138]
Hi,

Be careful, componentWillMount has been renamed and is not recommanded for use with React 16.9.0

Thx for the fix

**Comment by PeaGo** [comment]
Have you resolved this issue ?

**Comment by baconcheese113** [comment]
```
Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details.
    
    * Move data fetching code or side effects to componentDidUpdate.
    * If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
    * Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.
    
    Please update the following components: MultiSlider
```

Get this warning every time a the slider component is mounted

**Comment by sytolk** [comment]
Maybe this is fix for this issue:
https://github.com/ptomasroos/react-native-multi-slider/compare/master...balbirsng:master
@balbirsng what about to create new PR for this ?

**Comment by glburgess** [comment]
I am also getting this error message, it would be great if the previous mentioned fix worked or one was developed. Thank you in advance!

**Comment by sytolk** [comment]
I have tested it and no this "fix" not works.. but its appers that this project is not actively maintained @ptomasroos ?

**Comment by ptomasroos** [comment]
I’m currently not in the process of releasing updates to our apps. But feel free to send a pull request!

**Comment by sytolk** [comment]
ok you can review this :)
 https://github.com/ptomasroos/react-native-multi-slider/pull/151

**Comment by mitaxe** [comment]
Any updates?

**Comment by ptomasroos** [comment]
Fixed in master! Soon published

**Comment by baconcheese113** [comment]
@ptomasroos imo, this really shouldn't be closed until the fix is pushed to npm. Most of the users submitting issues here are still working off 1.0.0...which is almost 2 years outdated.

**Comment by ptomasroos** [comment]
Thanks for the feedback. But github closes all issues on merge of a pull request for instance. I haven’t seen a single repo keeping issues open until released.
