### ISSUE TITLE
Vertical Orientation

### ISSUE THREAD

**Issue by TheMarsGuy** [ptomasroos/react-native-multi-slider#15]
Does this package support vertical orientation? If not will this be added to the package sometime?

**Comment by ptomasroos** [comment]
Good one. Never thought about it. Should be quite easy. 

Wanna submit a pr?

**Comment by joshjconlin** [comment]
easy man, just play with the containerStyle, you should be able to do it pretty easy using flexbox

**Comment by ptomasroos** [comment]
Will close since its idling

**Comment by jchesne** [comment]
Is it possible to show an exemple on how to do this ?
