### ISSUE TITLE
Docs

### ISSUE THREAD

**Issue by bristoljon** [ptomasroos/react-native-multi-slider#16]
Are there any docs for this? Super confused as the api seems to be the same as [this package](https://github.com/JackDanielsAndCode/react-native-multi-slider) but there is no reference to it as far as I can see.

Thanks, Jon

**Comment by ptomasroos** [comment]
Hey @bristoljon 

The package you're referring to does not support Android.
Api is very much the same yes!

Docs are in the running example app which you can find in the repository
