### ISSUE TITLE
[BREAKING CHANGE] DefaultLabel shouldn't be shown by default

### ISSUE THREAD

**Issue by ivnnv** [ptomasroos/react-native-multi-slider#165]
Hi,
After updating my app to use the actual commit of the package (#75e9242 in the meantime you update the npm package), my customised slider showed two unexpected "floating labels" above the markers, which never were there:

Before:
![custom slider](https://user-images.githubusercontent.com/23552631/74350646-c2fbc580-4d94-11ea-99ae-de26f5236e2d.png)

·

After:
![floating-labels](https://user-images.githubusercontent.com/23552631/74350656-c8591000-4d94-11ea-880d-5b97c3a4f003.png)

This is definitely a breaking change and it should be documented accordingly, but I think ideal scenario would be just not showing the Label component by default plus the actual option to have it custom via customLabel prop:

```
showLabels: false,
customLabel: DefaultLabel,
```

and then in the render:
```
{showLabels && (
  <Label
     leftDiff={leftDiff}
    oneMarkerValue={this.state.valueOne}
    twoMarkerValue={this.state.valueTwo}
    oneMarkerLeftPosition={positionOne}
    twoMarkerLeftPosition={positionTwo}
    oneMarkerPressed={this.state.onePressed}
    twoMarkerPressed={this.state.twoPressed}
    />
}
```

So in the meantime, if someone has this same issue, the solution to hide the floating labels is  passing an empty `<View />` as the customLabel
```
<MultiSlider
  customLabel={() => <View />}
>
```

Please confirm if you agree with this and I can create the PR to fix this before you release the npm module because it will break every app that uses this package.

**Comment by ptomasroos** [comment]
Yes!

I've already created a commit for this locally,

A new prop called enableLabel.

Will commit this before making a real release, discovered it as well! Thanks for pointing out!
