### ISSUE TITLE
warnings - componentwillmount has been renamed and is not recommended for use

### ISSUE THREAD

**Issue by shachardevops** [ptomasroos/react-native-multi-slider#167]
- [x] I have searched [existing issues](https://github.com/ptomasroos/react-native-multi-slider/issues)
- [x] I am using the [latest multi slider version](https://www.npmjs.com/package/@ptomasroos/react-native-multi-slider)

**Comment by ptomasroos** [comment]
This is fixed in master, but waiting to be released after someone tries out the pending pull request
