### ISSUE TITLE
Labels do not show up at all

### ISSUE THREAD

**Issue by RandomSpectrum** [ptomasroos/react-native-multi-slider#171]
```
<MultiSlider
      containerStyle={{ height: 40 }}
      values={[value1, value2]}
      isMarkersSeparated
      sliderLength={300}
      enableLabel
      customLabel={() => <Text>Custom Label</Text>}
      min={0}
      max={100}
      enabledOne={false}
      enabledTwo={false}
      customMarkerLeft={marker}
      customMarkerRight={marker}
      selectedStyle={{
        backgroundColor: colors.purpleDark6,
        height: 2,
    }}
      unselectedStyle={{
        backgroundColor: colors.purpleDark5,
        height: 2,
    }}
/>
```

I see that a new property 'enableLabel' was introduced, but I have played around with it and some other properties and I cannot seem to get the labels to show up. Am I missing something?

**Comment by baconcheese113** [comment]
Are you using the latest version from github, or the one from 2 years ago through npm?

**Comment by ptomasroos** [comment]
I will publish the latest version to npm in just a few minutes!
Labels should then be visible, feel free to open up a new issue if it persists

**Comment by ptomasroos** [comment]
2.2.0 is now released feel free to try it out

**Comment by Anujmoglix** [comment]
My requirement is to show custom label with the different value in every step. Like Range value point .

**Comment by SpotHimesh** [comment]
Hey @Anujmoglix did you find a solution to your problem?
