### ISSUE TITLE
MultiSlider can't display completely in android

### ISSUE THREAD

**Issue by oporter1** [ptomasroos/react-native-multi-slider#173]
- [x] I have searched [existing issues](https://github.com/ptomasroos/react-native-multi-slider/issues)
- [x] I am using the [latest multi slider version](https://www.npmjs.com/package/@ptomasroos/react-native-multi-slider)

I have searched through all of the Android UI related questions and have asked on stackoverflow as well. I am unable to find a solution. 

I have updated all packages today and previous days. I am not seeing a version > 1 available. Please advise if there is a greater version. 

I am using: import MultiSlider from "@ptomasroos/react-native-multi-slider";  and:  "@ptomasroos/react-native-multi-slider": "^1.0.0",

and: 

    "@ptomasroos/react-native-multi-slider": {
      "version": "1.0.0",
      "resolved": "https://registry.npmjs.org/@ptomasroos/react-native-multi-slider/-/react-native-multi-slider-1.0.0.tgz",
      "integrity": "sha512-NpX22rQLArg9widwMzGf7XsInTDf6mfY/D1XaDVjglNkVphj3NSN37+nF6MofArCxC++1P+jHv0SGWbmJQwy4g=="
    },

I installed package, created my MultiSlider with markerStyle set. Move slider around and I can see the data is working appropriately but the UI is transparent. 

styles work on iPhone and not Android. I have tried to change the border color a to a number of different colors, and have tried setting all of these: {container/track/selected/unselected/ markerContainer/marker/pressedMarker} Style. The circles will not take a border color. 

## Steps to Reproduce

I installed package, created my MultiSlider with markerStyle set. Move slider around and I can see the data is working appropriately but the UI is transparent. 

styles work on iPhone and not Android. 

## Expected Behavior

Slide will be visible and have border colors for both circles on the slider. 

## Actual Behavior

Slider is working but circle colors are transparent. 

![image](https://user-images.githubusercontent.com/12777243/75807517-85ff6f00-5d53-11ea-943b-7dd432b710a4.png)

**Comment by ptomasroos** [comment]
Please make sure to use the latest version. Probably your lock file is restricting it from being downloaded?

**Comment by oporter1** [comment]
@ptomasroos what version should it be on? I don't have any restrictions on my lock file. I am on Expo which sometimes causes issues with packages...

**Comment by gr0x0** [comment]
Hi! I had the same issues on android, but I resolved it by setting backgroundColor and borderColor. For instance:

> <StyledSlider
> ...
> markerStyle={{backgroundColor: "white", borderColor: "black"}}
> ...
> />

In any case, setting elevation in markerStyle to some value higher then 0 might also work as a temporary solution, as it also did for me.

**Comment by oporter1** [comment]
this worked. I wanted to keep the circle white with the border color black but for whatever reason Android isn't picking up on that style. When I changed the background color to a solid color it is now visible. we can close this.

**Comment by peerawat-p** [comment]
I add style width border in markerStyle.
it worked.

```
<StyledSlider
...
markerStyle={{backgroundColor: "white", borderColor: "black", borderWidth: 1}}
...
/>
```
