### ISSUE TITLE
Custom Marker MultiSlider Problem on iOS

### ISSUE THREAD

**Issue by fredyonge** [ptomasroos/react-native-multi-slider#184]
##Description

  If I use a custom marker for slider, it shows a SplittingLine in the middle. This only happens on iOS , using two sliders, and a custom marker.

## Steps to Reproduce

`<MultiSlider
                        values={[values[0], values[1]]}
                        optionsArray={optionsArray}
                        selectedStyle={{
                            backgroundColor: COLOR_PRIMARY,
                            flex: 1,
                        }}
                        min={0}
                        max={500}
                        sliderLength={DIMENSION_WIDTH - 30 - 66}
                        snapped
                        onValuesChange={onValuesChange}
                        touchDimensions={{
                            height: 200,
                            width: 100,
                            borderRadius: 30,
                            slipDisplacement: 200,
                        }}
                        customMarker={SliderCustomMarker}
                    />.`

`const SliderCustomMarker = (props: Props) => {
    const {} = props;
    return (
        <View>
            <View
                style={{
                    width: 25,
                    height: 25,
                    backgroundColor: COLOR_PRIMARY,
                    borderRadius: 15,
                }}
            />
        </View>
    );
};`

## Expected Behavior

 See Top Slider
  https://ibb.co/0jp9XtJ

## Actual Behavior

See bottom slider 
https://ibb.co/0jp9XtJ

Thanks a lot!

**Comment by ptomasroos** [comment]
Can you explain what you fixed @fredyonge ?

**Comment by jaroslav009** [comment]
same issue

**Comment by fuadhasanEWU** [comment]
When max and min value same and then try to slide app got crashed and show this error

*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Multiplier is not finite!  That's illegal.  multiplier:inf'
