### ISSUE TITLE
Can't slide to the maximum value

### ISSUE THREAD

**Issue by satasuk01** [ptomasroos/react-native-multi-slider#187]
<MultiSlider
            values={[props.answerVal.duration]}
            onValuesChange={(value)=>answer(value, 'duration')}
            max={6}
            min={2}
            step={1}
            // containerStyle={styles.stepContainer}
            sliderLength={410}
            selectedStyle={{ backgroundColor: 'rgb(37, 75, 135)' }}
            unselectedStyle={{ backgroundColor: 'rgb(37, 75, 135)' }}
            snapped
          />

**I can't slide any further**
![Wall](https://user-images.githubusercontent.com/31332172/79312983-e4f6fd00-7f29-11ea-8e32-3e90e1af84f1.jpg)

**Comment by satasuk01** [comment]
after restarting Expo, It's worked fine.

**Comment by jeremyblalock** [comment]
Still having this issue. Is anyone else experiencing this?

In our example we have a single slider marker, and `snapped` is `false`.

**Comment by aborile** [comment]
Still having this issue.
Not using expo, and I have single slider marker, snapped is false
```
<MultiSlider
          sliderLength={metrics.screenWidth - 120}
          min={0}
          max={3}
          values={values}
          onValuesChangeFinish={onValuesChange}
          trackStyle={styles.sliderTrackStyle}
          selectedStyle={styles.sliderTrackStyle}
          snapped
          customMarker={() => <View style={styles.sliderMarker} />}
 />
```

The weird thing is that sliding to the maximum value at first is working. But when i slide to another value, from then it doesn't slide to the maximum value anymore

**Comment by calinbodnar** [comment]
The workaround that worked for me was to use `allowOverlap={true}`

**Comment by Saad-Bashar** [comment]
Yeah, allowOverlap={true} works when we only have one element inside values.
