### ISSUE TITLE
programatically move slider with function..is it possible?

### ISSUE THREAD

**Issue by Aryk** [ptomasroos/react-native-multi-slider#198]
I'm on 2.2.2 of the slider. I can upgrade if needed.

Anyway to programatically move the sliider. 

I noticed that once it gets set according to the first initial value, there is no way to move it without touch the display and moving the slider.

I would like to for example, move to a different index on the slider based on options selected on a different screen while the previous screen was mounted.

Anyways to expost a ref and do like ref.current.moveTo? Didn't see it in the documentation.

**Comment by ptomasroos** [comment]
Or create a new component by changing the key={new value}

**Comment by Aryk** [comment]
Fair enough, I will try that! Thx
