### ISSUE TITLE
Markers cannot be dragged from the overflowing side on Android

### ISSUE THREAD

**Issue by raynor85** [ptomasroos/react-native-multi-slider#199]
- [x] I have searched [existing issues](https://github.com/ptomasroos/react-native-multi-slider/issues)
- [x] I am using the [latest multi slider version](https://www.npmjs.com/package/@ptomasroos/react-native-multi-slider)

On Android, when the marker is on the right or left edge, the half part that overflow out from the track doesn't receive touches, therefore it is not possible to drag it

## Expected Behavior
You should be able to drag it, or even better, it would be great if the marker doesn't overflow the track #45 

## Actual Behavior
It overflows the track and the overflowing part is not draggable

I have created a PR that fixes it, which also fixes #45 
#196

**Comment by TomasSestak** [comment]
It doesn't work for me when using custom Element as Indicator
