### ISSUE TITLE
Update `CHANGELOG.md`

### ISSUE THREAD

**Issue by Morgan-jarry** [ptomasroos/react-native-multi-slider#219]
Could you please rename `CHANGELOG` to `CHANGELOG.md` and keep it up to date ?
I'm on a project that uses your library and it uses the v1. I don't know what are the breaking changes on v2 since you don't keep it up to date.

**Comment by ptomasroos** [comment]
We moved over to GitHub releases hence there was no further updated to the CHANGELOG file.

https://github.com/ptomasroos/react-native-multi-slider/releases
