### ISSUE TITLE
touchDimensions not used

### ISSUE THREAD

**Issue by JonasWho** [ptomasroos/react-native-multi-slider#23]
touchDimensions.height and touchDimensions.width don't seem to be used for anything in MultiSlider.js?

**Comment by ptomasroos** [comment]
Hey, yep seems like a miss!
Wanna send a PR to remove them?

**Comment by JonasWho** [comment]
@ptomasroos but shouldn't they be implemented instead? I might have fixed them so that they work. Still testing...

**Comment by ptomasroos** [comment]
Any news @JonasWho ?

**Comment by Alpume** [comment]
Hi @ptomasroos, I've seen that this issue isn't solved in the current version, but I think it's a something useful. Is there any possibility to solve this in next release?.

**Comment by ptomasroos** [comment]
Hi there @Alpume !

Can you tell me what the fixed would be ? Remove it or implement it?

**Comment by Alpume** [comment]
Hi again,

I was little explanatory, sorry. I meant implement it.

**Comment by ptomasroos** [comment]
Feel free to send a pull request @Alpume !
We're happy with the default touchpoints used in our app so I do not intend to implement it at this moment
