### ISSUE TITLE
The value range are only for 0 to 10?

### ISSUE THREAD

**Issue by tsaohucn** [ptomasroos/react-native-multi-slider#24]
I used multi-slider and set the value for example [20,50], bit it doesn't work, it only work when I set value [0.10] or [3,7] .., so it seems the value   range are limited in 0~10 ?

**Comment by ptomasroos** [comment]
Have you tried passing in the props, min, max, step?

These are by default

```
    step: 1,
    min: 0,
    max: 10,
```

**Comment by ptomasroos** [comment]
@tsaohucn 

Did you get it up and running?

**Comment by tsaohucn** [comment]
@ptomasroos , I set  the props, min, max, step, and it work now, thanks, but is there any document describe the API information ?

**Comment by ptomasroos** [comment]
Will add to the readme. Feel free to send a pr. 

Otherwise the runnable example. 

Glad it worked out!

**Comment by fauzzi** [comment]
I have same issue with multi slider,  I set value  [0, 100000000] 
 step: 1,
 min: 0,
 max: 100000000,
The app crash

**Comment by ptomasroos** [comment]
Aouch! Never tried it with 100000000, feel free to send a PR if you can get it working! Just edit the component in your node modules! @fauzzi

**Comment by saurabhpandey16** [comment]
@fauzzi FACING SAME ISSUE.

**Comment by AishwaryaSurana** [comment]
@fauzzi Same happened with me. How were you able to correct? Is there any addition for big max value till now @ptomasroos
