### ISSUE TITLE
Min Max Slider Marker Issue

### ISSUE THREAD

**Issue by VinitBhavsar** [ptomasroos/react-native-multi-slider#245]
- [x] I have searched [existing issues](https://github.com/ptomasroos/react-native-multi-slider/issues)
- [ ] I am using the [latest multi slider version](https://www.npmjs.com/package/@ptomasroos/react-native-multi-slider)

## Steps to Reproduce
`
 <MultiSlider
enabledOne={true} enabledTwo={true}
isMarkersSeparated={true}
onValuesChange={(value) => {
  let val = value.toString().split(",") 
   this.setState({ minAge: val[0], maxAge: val[1] })  }}
     max={60} min={18}
      sliderLength={SCREEM_WIDTH - 90}
           values={[minAge, maxAge]}
              onToggleOne={() => { }} onToggleTwo={() => { }}
              allowOverlap={false}
                                            minMarkerOverlapDistance={10} minMarkerOverlapStepDistance={10}
                                        />
`

## Expected Behavior
![Screenshot_1629716850](https://user-images.githubusercontent.com/39370546/130437822-7733ade1-fc82-43ab-ad67-f4db222fed64.png)

## Actual Behavior
![Screenshot_1629716615](https://user-images.githubusercontent.com/39370546/130437833-c382617b-60e0-4a35-83e0-b974ebee90b1.png)

**Comment by faizansohail077** [comment]
Did you find the answer to this ? facing same issue.

**Comment by VinitBhavsar** [comment]
Nope @faizansohail077

**Comment by VinitBhavsar** [comment]
@faizansohail077 
Try min-max value in single state.
`
minMax: [23,28]
`
Slider Props:
`
 <MultiSlider 
enabledOne={true} enabledTwo={true}
isMarkersSeparated={true}
onValuesChange={(value) => { this.setState({ minMax: value }) }}
max={60} min={18}
values={this.state.minMax}
allowOverlap={false}
/>
`

**Comment by Anant5555** [comment]
> @faizansohail077
> Try min-max value in single state.
> `minMax: [23,28]`
> Slider Props:
> `<MultiSlider enabledOne={true} enabledTwo={true} isMarkersSeparated={true} onValuesChange={(value) => { this.setState({ minMax: value }) }} max={60} min={18} values={this.state.minMax} allowOverlap={false} />`

Hi Vinit, this one didnt fix it... Were you able the issue? I am facing the same

**Comment by VinitBhavsar** [comment]
@Anant5555 can you share your code?
