### ISSUE TITLE
Color of track before left marker

### ISSUE THREAD

**Issue by hophoppoppop** [ptomasroos/react-native-multi-slider#249]
- [X] I have searched [existing issues](https://github.com/ptomasroos/react-native-multi-slider/issues)
- [X] I am using the [latest multi slider version](https://www.npmjs.com/package/@ptomasroos/react-native-multi-slider)

can i make color track from before left marker different than track between marker and after right marker? (like image below
![image](https://user-images.githubusercontent.com/14010811/136695461-92d91aed-5b37-40b7-bafc-b5b37025ab74.png)

## Steps to Reproduce
-

## Expected Behavior
-

## Actual Behavior
-

**Comment by 0hio-creator** [comment]
@hophoppoppop 
Ran into this.
The code as is  doesn't support it.
I made a fork to add this functionality. https://github.com/0hio-creator/react-native-multi-slider
