### ISSUE TITLE
Markers

### ISSUE THREAD

**Issue by Per77070** [ptomasroos/react-native-multi-slider#258]
Hi!

The Multislider only shows one marker. How do I make it show two?

Best regards
Per

**Comment by usamaabutt** [comment]
yes, how to show two markers?

**Comment by Per77070** [comment]
Yes, please. :) I would like some help. I tried to follow your example, but I seem to be doing something wrong.

**Comment by KyawSoeHein** [comment]
Give it two values like values=[0,1]. The second marker will appear.

**Comment by angelxmoreno** [comment]
@Per77070 could you close this issue as resolved?
