### ISSUE TITLE
Allow custom left/right marker offsets

### ISSUE THREAD

**Issue by janneklouman** [ptomasroos/react-native-multi-slider#26]
I want to adjust the `left` and `right` properties of `markerContainerOne` and `markerContainerTwo` respectively, to mimic the the `react-native` `Slider`'s marker behavior (which uses marker outer edge as "value indicator", rather than the center of the marker like this component). However it seems the value 24 is hardcoded:

```JS 
const markerContainerOne = { top: -24, left : trackOneLength - 24 }
const markerContainerTwo = { top: -24, right: trackThreeLength - 24 };
```

I'm not sure what the best solution to this is, perhaps adding custom offset props?

```JS 
static defaultProps = {
  markerOffsetX: 0,
  markerOffsetY: 0,
 // ...
}
```
```JS 
const { markerOffsetX, markerOffsetY } = this.props;
const markerContainerOne = { top: markerOffsetY - 24, left : trackOneLength + markerOffsetX - 24 }
const markerContainerTwo = { top: markerOffsetY - 24, right: trackThreeLength + markerOffsetX - 24 };
```

I can then do following to solve my problem.
```JS
<MultiSlider markerOffsetX={14} ...
```

Thoughts on this?

**Comment by ptomasroos** [comment]
Yes!

That sounds like a viable solution. Sorry for it being hardcoded. 

Do you mind sending a pull request?

**Comment by janneklouman** [comment]
Thank you for the quick response!

I've created a pull request https://github.com/ptomasroos/react-native-multi-slider/pull/27
