### ISSUE TITLE
Slider is not smooth

### ISSUE THREAD

**Issue by musabgulfam** [ptomasroos/react-native-multi-slider#264]
- [x] I have searched [existing issues](https://github.com/ptomasroos/react-native-multi-slider/issues)
- [x] I am using the [latest multi slider version](https://www.npmjs.com/package/@ptomasroos/react-native-multi-slider)

The slider is not sliding as expected, it is not sliding smoothly, instead it is sliding in an awkward motion, i.e. it's frequently stopping and sliding.

## Steps to Reproduce

Here's is the code
```
<MultiSlider
          values={[minPrice, maxPrice]}
          sliderLength={200}
          onValuesChange={handleValueChange}
          max={200}
          smoothSnapped={false}
          thumbTintColor={colors.secondaryColor}
          // touchDimensions={{
          //   height: 20,
          //   width: 20,
          //   borderWidth: 50
          // }}
/>

const handleValueChange = useCallback((val) => {
    setMaxPrice(val[1]);
    setMinPrice(val[0]);
    setFilterPayload({
      ...filterPayload,
      price: {
        min: val[0],
        max: val[1]
      }
    })
  }, []);
```

**Comment by musabgulfam** [comment]
???

**Comment by JDMathew** [comment]
If you set `smoothSnapped={true}` does this fix your problem? It will then snap on release.

**Comment by musabgulfam** [comment]
Alright, after a long time, I did observe a solution. Using `onValueChange` props is a bad idea. If you were to make it smooth, use the prop `enableLabel`, with a `customLabel` component which has the min and max values in its props to render the min and max values, and use the `onValueChangeFinish` prop to set the min and max values. So the final solution may look something like this.

```
       <MultiSlider
          values={[minPrice, maxPrice]}
          sliderLength={200}
          onValuesChangeFinish={handleValueChange}
          max={200}
          smoothSnapped={true}
          thumbTintColor={colors.secondaryColor}
          enableLabel
          customLabel={props => {
            return (
              <View>
                <Text style={{
                  color: '#121212',
                  fontSize: 25,
                  fontFamily: 'Oswald-Bold',
                  marginBottom: 10
                }}>${props.oneMarkerLeftPosition.toFixed(0)} - ${props.twoMarkerLeftPosition.toFixed(0)}</Text>
              </View>
            )
          }}
          step={1}
        />
```

**Comment by manjubhatt** [comment]
> Alright, after a long time, I did observe a solution. Using `onValueChange` props is a bad idea. If you were to make it smooth, use the prop `enableLabel`, with a `customLabel` component which has the min and max values in its props to render the min and max values, and use the `onValueChangeFinish` prop to set the min and max values. So the final solution may look something like this.
> 
> ```
>        <MultiSlider
>           values={[minPrice, maxPrice]}
>           sliderLength={200}
>           onValuesChangeFinish={handleValueChange}
>           max={200}
>           smoothSnapped={true}
>           thumbTintColor={colors.secondaryColor}
>           enableLabel
>           customLabel={props => {
>             return (
>               <View>
>                 <Text style={{
>                   color: '#121212',
>                   fontSize: 25,
>                   fontFamily: 'Oswald-Bold',
>                   marginBottom: 10
>                 }}>${props.oneMarkerLeftPosition.toFixed(0)} - ${props.twoMarkerLeftPosition.toFixed(0)}</Text>
>               </View>
>             )
>           }}
>           step={1}
>         />
> ```

In customLabel i am not able to set the range input using min and max. By default its picking the sliderLength as min and max. any solution?
