### ISSUE TITLE
CustomLeftMarker & CustomRightMarker not working

### ISSUE THREAD

**Issue by margretheluth** [ptomasroos/react-native-multi-slider#277]
- [  ] I have searched [existing issues](https://github.com/ptomasroos/react-native-multi-slider/issues)
- [ ] I am using the [latest multi slider version](https://www.npmjs.com/package/@ptomasroos/react-native-multi-slider)

I can't get the CustomLeftMarker & CustomRightMarker to work, is this a know problem? In the code below the customMarkerLeft  is still the same as the default. I have tried to the customMarker but then they are styled the same.
  
```
  customMarkerLeft={() => CustomMarker(startTimeSlider)}
  import colors from '../../../../theme/colors';
  export const CustomMarker =( value)=>{
  console.log(value)
      return (
        <View style={styles.markerContainer}>
        </View>
      );
    };
    const styles = StyleSheet.create({
      markerContainer:{
        backgroundColor: colors.buttonDarkGreen,
        padding: 10,
        width: 20,
        height:20
      }
    });

```

**Comment by Djiypyk** [comment]
not fixed?
