### ISSUE TITLE
Need to update latest version with npm

### ISSUE THREAD

**Issue by easilver** [ptomasroos/react-native-multi-slider#28]
I'm finding this multi-slider really handy, but the library in npm is out of date; when I install I am not getting your most recent changes. Would you be able to update that? 

I would really love to use the enable/disable functionality you added a few months back but I'm not getting those changes when I npm install.

**Comment by ptomasroos** [comment]
I will fix that on Monday. Sorry for not releasing a version sooner.

**Comment by ptomasroos** [comment]
A new version 0.0.9 has been published to npm!
