### ISSUE TITLE
max value 

### ISSUE THREAD

**Issue by sandeep855** [ptomasroos/react-native-multi-slider#281]
if you pass a value in max greater than 6 digits eg: max={9999999} It hangs your device to load this value. Sometimes crashes the app.

**Comment by sheralim012** [comment]
https://github.com/ptomasroos/react-native-multi-slider/blob/7919a26fbda0a7aed00f25409b6dac81e8cac457/converters.js#L84-L86

For very large min & max and very small step, above loop generates very large array which causes the crash. Better to dynamically use the step value like 

```
step = Math.round(Math.abs(max - min) / 100)
```

This will force the loop to execute only 100 times.

Hope this helps.

**Comment by ptomasroos** [comment]
Thanks! Added to the readme @sheralim012
