### ISSUE TITLE
sliderValueChangeStart not firing

### ISSUE THREAD

**Issue by jackread** [ptomasroos/react-native-multi-slider#31]
Should this...
<pre><code>startOne = () => {
    if (this.state.enabledOne) {
      this.props.onValuesChangeStart();
      this.setState({
        onePressed: !this.state.onePressed,
      });
    }
  };

  startTwo = () => {
    if (this.state.enabledTwo) {
      this.props.onValuesChangeStart();
      this.setState({
        twoPressed: !this.state.twoPressed,
      });
    }
  };</code></pre>

be this?
<pre><code>startOne = () => {
    if (this.props.enabledOne) {
      this.props.onValuesChangeStart();
      this.setState({
        onePressed: !this.state.onePressed,
      });
    }
  };

  startTwo = () => {
    if (this.props.enabledTwo) {
      this.props.onValuesChangeStart();
      this.setState({
        twoPressed: !this.state.twoPressed,
      });
    }
  };</code></pre>

**Comment by ptomasroos** [comment]
Yes that bug was just fixed a day a go. 
If you update to the latest version it should be working as expected. 

Thank you very much for finding the bug!
