### ISSUE TITLE
Allow vertical orientation

### ISSUE THREAD

**Issue by jchesne** [ptomasroos/react-native-multi-slider#32]
Hello,

I would like to use this component vertically, do you think it is possible ?

**Comment by ptomasroos** [comment]
I will try to add it to the example repo during next week! @jchesne

**Comment by chrise86** [comment]
@ptomasroos would you suggest to just use a transform and rotate the component?

**Comment by ptomasroos** [comment]
@chrise86 yes tried it out and it doesn't work out as you're saying since transform doesn't affect the pan responders

**Comment by ptomasroos** [comment]
Closed in https://github.com/ptomasroos/react-native-multi-slider/commit/ccf2fda4b4e72f0d7adb61ef69abc0d8b3446366
