### ISSUE TITLE
Marker size on Android

### ISSUE THREAD

**Issue by damikdk** [ptomasroos/react-native-multi-slider#33]
Thank you for library. It's only way to make filters on android, but I have issue.

When I touch marker and release it, marker getting small. For the next time, it will returns to initial size. It is only happened with delay on touch out, only on Android.

I see, it should be like native Android slider (regular size marker - touch in - big size marker - touch out - regular size marker), but it's not. Can you help?

**Comment by ptomasroos** [comment]
Hey @damikdk I will try to check this issue during next week!

**Comment by damikdk** [comment]
Any news? I forgot to say, we use Expo!

**Comment by ptomasroos** [comment]
Hey @damikdk sorry for being a bit slow on this, if you could give me a hand with creating a reproduction example in expo I will make sure to fix the bug. Does that sound like a good deal?

**Comment by damikdk** [comment]
Sorry, but I can't even run this [expo snack](https://snack.expo.io/HJcGra0YZ). I have issue even on default slider, on any real android device with Expo.

**Comment by damikdk** [comment]
I got something! There is some dependence on marker size:

Bad style with bug on Android:
```
track: {
  borderRadius: 5,
  height: 5,
},
marker: {
  height: 30,
  width: 30,
  borderRadius: 15,
  borderWidth: 8,
},
sliderContainer: {
  paddingTop: 15
},
```

Good style, perfect work on Android without any transformations:
```
track: {
  borderRadius: 5,
  height: 9,
},
marker: {
  height: 20,
  width: 20,
  borderRadius: 10,
  borderWidth: 5,
  marginTop: 8,
},
sliderContainer: {
  paddingTop: 21
},
```

It's exactly what I need in my project, but issue still open.
One more time, thanks for your lib!
