### ISSUE TITLE
Custom Marker keeps flickering on every render

### ISSUE THREAD

**Issue by RyanMitchellWilson** [ptomasroos/react-native-multi-slider#38]
I'm trying to set up a slider with a custom marker that moves with a an updating value. But every time a render is called the Custom marker flickers and makes it hard to grab. If I remove the custom marker the standard marker works perfectly, no flickering and easy to grab. 

Here is my slider:
```
<Multislider
  customMarker={() => <Image source={scrubber}/>}
  sliderLength={Dimensions.get('window').width - 40}
  touchDimensions={{width: 50, height: 50}}
  values={[Math.round(slowRacer.currentIndex || 0)]}/>
```

**Comment by ptomasroos** [comment]
You should probably preload the images here and not call them inline required, rather require them all and change it during runtime since its already. Just a feeling

**Comment by RyanMitchellWilson** [comment]
I am preloading the image, at the very top of the file completely outside of my react-native component I do `const scrubber = require(<PathToMyFile>)` yet every render it still flashes.

**Comment by ptomasroos** [comment]
Can you post the complete example with a example repo and I will def take a look at it!

**Comment by sadeghipour** [comment]
@RyanMitchellWilson you can fix this problem witg separate markers in new update.

**Comment by FarzanAkhtar** [comment]
I am having the exact same issue..is there a workaround??
