### ISSUE TITLE
disable prop for multislider component

### ISSUE THREAD

**Issue by iltoga** [ptomasroos/react-native-multi-slider#40]
Hi and first off thanks for the good component I would love to use on my app, but I cannot at the moment because I can't find a way to disable both markers (I have an edit screen component that must render the slider component 'disabled and greyed out' if user is not in 'edit' mode).
Do you plan to add this functionality in the near future?
Cheers

**Comment by iltoga** [comment]
I've already answered myself by setting enabledOne and enabledTwo props to false :+1:

**Comment by ptomasroos** [comment]
👍
