### ISSUE TITLE
Add ability to limit how often onValuesChange fires

### ISSUE THREAD

**Issue by RyanMitchellWilson** [ptomasroos/react-native-multi-slider#41]
I'm currently running some calculations every time the value changes when I'm sliding it, but I would like it to only fire the onValuesChange method a couple times every second.

Is there a way to limit this currently? I wasn't able to see anything popping out at me in the source code for this project. If not could it possibly be added?

**Comment by ptomasroos** [comment]
Not really. But yeah if you just use underscore / lodash and use the _.throttle on the callback with, 1000 as the rate it should be fine.

**Comment by ptomasroos** [comment]
Actually debounce would be better here since you're probably looking to do a calculation of the last value provided!

**Comment by ptomasroos** [comment]
http://underscorejs.org/#debounce

**Comment by RyanMitchellWilson** [comment]
That could work but I'm not exactly trying to pull in another library for this one thing but I did manage to get what I need just by setting a timestamp whenever `onValueChanges` runs and I only run the calculations if the two times are enough apart.

**Comment by ptomasroos** [comment]
Well done! Glad you solved it !
