### ISSUE TITLE
Stop working on latest RN 0.49.3

### ISSUE THREAD

**Issue by greenais** [ptomasroos/react-native-multi-slider#42]
Build is successful, but running on Android simulator brings an error:

undefined is not an object (evaluating 'PropTypes.bool')

with references to files in node_modules/react-native-multi-slider/
mockProps.js:15:23
Slider.js:16:24
along with plenty of /metro-bundler/src/Resolver/polifills/require.js

Worked fine on RN 0.48.4
Any suggestions, perhaps?

**Comment by ptomasroos** [comment]
I'm pretty sure you're using another npm package considering the path. 

Either switch or find the appropriate repo. Best of luck.

**Comment by greenais** [comment]
You are right, I missed the point that yours one installs with @ptomasroos/react-native-multi-slider, I just used npm i react-native-multi-slider
Never met such synonyms on npm yet...
Thank you, everything works fine.
Good job!
