### ISSUE TITLE
Cannot read property bool of undefined

### ISSUE THREAD

**Issue by lXSPandora** [ptomasroos/react-native-multi-slider#44]
When i import the MultiSlider this error shows up

![simulator screen shot - iphone 6 - 2017-12-01 at 12 51 40](https://user-images.githubusercontent.com/18129416/33488013-681f872c-d696-11e7-8ce0-784dd02ba347.png)

**Comment by ptomasroos** [comment]
Can you post your package.json?

**Comment by lXSPandora** [comment]
{
  "name": "Natura",
  "version": "1.7.3",
  "config": {
    "commitizen": {
      "path": "./node_modules/cz-conventional-changelog"
    }
  },
  "dependencies": {
    "@entria/formia": "^0.0.10",
    "@entria/utils": "^0.0.10",
    "@expo/ex-navigation": "git+https://git@github.com/entria/ex-navigation.git#cb5211552b29e660d7374e5057dc40ad4146eeb5",
    "@expo/react-native-action-sheet": "^1.0.1",
    "babel-preset-react-native-stage-0": "^1.0.1",
    "base-64": "^0.1.0",
    "buffer": "^5.0.7",
    "d3": "4.10.0",
    "d3-shape": "^1.2.0",
    "date-fns": "^1.29.0",
    "deepmerge": "^1.5.1",
    "fbjs": "^0.8.15",
    "hoist-non-react-statics": "^2.3.1",
    "idx": "^1.5.0",
    "lodash": "^4.17.4",
    "lodash.get": "^4.4.2",
    "lodash.isequal": "^4.5.0",
    "lodash.set": "^4.3.2",
    "moment": "^2.18.1",
    "numeral": "^2.0.6",
    "pretty-format": "^21.2.1",
    "prop-types": "^15.5.10",
    "query-string": "^5.0.0",
    "react": "16.0.0",
    "react-addons-shallow-compare": "^15.5.2",
    "react-native": "0.50.3",
    "react-native-action-button": "^2.8.3",
    "react-native-aws3": "^0.0.8",
    "react-native-button": "^2.1.0",
    "react-native-calendar": "^0.13.1",
    "react-native-calendars": "^1.14.2",
    "react-native-camera": "^0.12.0",
    "react-native-camera-roll-picker": "^1.2.3",
    "react-native-chart": "^1.0.8-beta",
    "react-native-checkbox-field": "^2.0.2",
    "react-native-collapsible": "^0.9.0",
    "react-native-device-info": "^0.12.1",
    "react-native-dotenv": "^0.1.0",
    "react-native-fabric": "^0.5.0",
    "react-native-fetch-blob": "^0.10.8",
    "react-native-fontawesome": "^5.7.0",
    "react-native-globalize": "^1.2.2",
    "react-native-google-analytics-bridge": "^5.3.3",
    "react-native-i18n": "^2.0.9",
    "react-native-image-crop": "git+https://git@github.com/entria/react-native-image-crop.git#4074409183f5dfd6e91bf612bbf4062df47cee02",
    "react-native-image-progress": "^1.0.1",
    "react-native-image-resizer": "1.0.0",
    "react-native-keyboard-aware-scroll-view": "^0.4.1",
    "react-native-keyboard-spacer": "^0.4.1",
    "react-native-linear-gradient": "^2.3.0",
    "react-native-looped-carousel": "^0.1.7",
    "react-native-maps": "^0.17.1",
    "react-native-modal-datetime-picker": "^4.11.0",
    "react-native-modal-picker": "0.0.16",
    "react-native-multi-slider": "^0.3.6",
    "react-native-share": "^1.0.23",
    "react-native-simple-gauge": "^0.1.4",
    "react-native-sms": "^1.5.0",
    "react-native-snap-carousel": "^3.2.1",
    "react-native-svg": "6.0.0",
    "react-native-tab-view": "^0.0.70",
    "react-native-tableview-simple": "^0.17.1",
    "react-native-text-input-reset": "^1.0.2",
    "react-native-uuid": "^1.4.9",
    "react-native-view-shot": "^2.2.0",
    "react-redux": "^5.0.6",
    "react-relay": "^1.4.1",
    "react-test-context-provider": "^2.1.2",
    "recompose": "^0.26.0",
    "redux": "^3.7.2",
    "redux-logger": "^3.0.4",
    "redux-persist": "^4.9.1",
    "rn-splash-screen": "^5.2.0",
    "string-mask": "^0.3.0",
    "styled-components": "^2.1.2",
    "tcomb-form-native": "^0.6.8"
  },
  "detox": {
    "test-runner": "jest",
    "specs": "e2e",
    "configurations": {
      "ios.sim.release": {
        "binaryPath": "ios/build/Build/Products/Release-iphonesimulator/Natura.app",
        "build": "export RCT_NO_LAUNCH_PACKAGER=true && xcodebuild -project ios/Natura.xcodeproj -scheme Natura -configuration Release -sdk iphonesimulator -derivedDataPath ios/build",
        "type": "ios.simulator",
        "name": "iPhone 7 Plus"
      },
      "ios.sim.debug": {
        "binaryPath": "ios/build/Build/Products/Debug-iphonesimulator/Natura.app",
        "build": "xcodebuild -project ios/Natura.xcodeproj -scheme Natura -configuration Debug -sdk iphonesimulator -derivedDataPath ios/build",
        "type": "ios.simulator",
        "name": "iPhone 7 Plus"
      },
      "android.emu.debug": {
        "binaryPath": "android/app/build/outputs/apk/app-debug.apk",
        "build": "pushd android && ./gradlew assembleDebug assembleAndroidTest -DtestBuildType=debug && popd",
        "type": "android.emulator",
        "name": "Nexus_5X_API_25"
      },
      "android.emu.release": {
        "binaryPath": "android/app/build/outputs/apk/app-release.apk",
        "build": "pushd android && ./gradlew assembleRelease assembleAndroidTest -DtestBuildType=release && popd",
        "type": "android.emulator",
        "name": "Nexus_5X_API_25"
      }
    }
  },
  "devDependencies": {
    "@storybook/react": "3.2.16",
    "@storybook/react-native": "3.2.16",
    "babel-eslint": "^8.0.2",
    "babel-jest": "^21.2.0",
    "babel-plugin-functional-hmr": "^1.0.22",
    "babel-plugin-relay": "^1.4.1",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-react": "^6.24.1",
    "babel-preset-react-native": "4.0.0",
    "babel-preset-stage-0": "^6.24.1",
    "concurrently": "^3.5.0",
    "cz-conventional-changelog": "^2.0.0",
    "detox": "^6.0.2",
    "enzyme": "^3.2.0",
    "eslint": "^4.12.0",
    "eslint-plugin-flowtype": "^2.39.1",
    "eslint-plugin-import": "^2.7.0",
    "eslint-plugin-react": "^7.3.0",
    "eslint-plugin-react-native": "^3.2.0",
    "flow-bin": "^0.59.0",
    "jest": "^21.2.1",
    "jest-cli": "^21.1.0",
    "jest-react-native": "18.0.0",
    "lint-staged": "^5.0.0",
    "pre-commit": "^1.2.2",
    "prettier": "^1.7.0",
    "react-addons-test-utils": "^15.5.1",
    "react-dom": "^16.1.1",
    "react-native-schemes-manager": "^1.0.1",
    "react-test-renderer": "~16.1.1",
    "redux-mock-store": "^1.3.0",
    "relay-compiler": "^1.4.1",
    "relay-devtools": "^1.4.0",
    "stylelint": "^8.3.1",
    "stylelint-config-standard": "^18.0.0",
    "stylelint-config-styled-components": "^0.1.1",
    "stylelint-processor-styled-components": "^1.1.1"
  },
  "jest": {
    "setupTestFrameworkScriptFile": "./e2e/init.js"
  },
  "lint-staged": {
    "*.js": [
      "yarn prettier",
      "eslint --fix",
      "git add"
    ]
  },
  "pre-commit": "lint:staged",
  "private": true,
  "scripts": {
    "android:apk": "cd android && ./gradlew assembleRelease",
    "android:apk:production": "yarn config:production && cd android && ./gradlew assembleRelease",
    "android:apk:staging": "yarn config:staging && cd android && ./gradlew assembleRelease",
    "android:dynatrace": "../natura-dynatrace/Android/auto-instrumentor/instrument.sh apk=app-fv.apk prop=app-fv.properties",
    "android:install": "adb install android/app/build/outputs/apk/app-release.apk",
    "build:production": "cp .env.prod .env.production",
    "build:staging": "cp .env.staging .env.development && cp .env.staging .env.production",
    "clear": "node node_modules/react-native/local-cli/cli.js start --reset-cache",
    "clear:relay": "concurrently --kill-others \"node node_modules/react-native/local-cli/cli.js start --reset-cache\" \"yarn relay:watch\"",
    "config:production": "cp .env.prod .env.development && cp .env.prod .env.production",
    "config:staging": "cp .env.staging .env.development && cp .env.staging .env.production",
    "devtools": "react-devtools",
    "e2e": "jest __e2e__ --setupTestFrameworkScriptFile=./jest/setup-e2e-tests.js --bail",
    "fix-xcode": "react-native-schemes-manager all",
    "flow": "flow; test $? -eq 0 -o $? -eq 2",
    "ios:ipa": "react-native bundle --dev false --entry-file index.ios.js --bundle-output ios/main.jsbundle --platform ios",
    "lint": "eslint src",
    "lint:css": "stylelint './src/**/*.js'",
    "lint:staged": "lint-staged",
    "prettier": "prettier --write --single-quote true --trailing-comma all --print-width 120",
    "relay": "relay-compiler --src ./src --schema data/schema.graphql",
    "relay:watch": "yarn relay --watch",
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "storybook": "storybook start -p 7007",
    "test": "jest --config jest/jest.config.json",
    "test-ios": "detox build --configuration ios.sim.debug && detox test --configuration ios.sim.debug",
    "test-android": "detox build --configuration android.emu.debug && detox test --loglevel verbose --configuration android.emu.debug",
    "release:major": "npm version major && git push --follow-tags",
    "release:minor": "npm version minor && git push --follow-tags",
    "release:patch": "npm version patch && git push --follow-tags"
  },
  "xcodeSchemes": {
    "Debug": [
      "Staging"
    ],
    "Release": [],
    "projectDirectory": "iOS"
  }
}

**Comment by ptomasroos** [comment]
That's not this component !

**Comment by yummyelin** [comment]
Is it possible to change the package name? like 'react-native-easy-slider', 'react-native-advanced-slider'

**Comment by ptomasroos** [comment]
Sadly it will break the existing clients since they won't get upgrades until they discover it's dead

**Comment by yummyelin** [comment]
Understand..Thanks for answering me
