### ISSUE TITLE
Markers

### ISSUE THREAD

**Issue by Unlighten** [ptomasroos/react-native-multi-slider#45]
Which property would I call in order to change the style of the markers?

Currently the markers go over the side of the line and I am trying to get the edge of the marker to touch the edge of the line.

This is what it looks like in case my description wasn't helpful:
https://imgur.com/a/GKp2y

The top image is what I want, the bottom image is what is currently happening.

**Comment by Kyonru** [comment]
I suggest using the half of the with of the marker as margin left/right.

**Comment by ptomasroos** [comment]
Has this been resolved @Unlighten ?

**Comment by Unlighten** [comment]
No

**Comment by manuvincent** [comment]
Add markerOffsetX property to multislider where value is width of marker/2

**Comment by ptomasroos** [comment]
@manuvincent could you add this to the readme would be great or even in the example app.
