### ISSUE TITLE
weird bug on multiple values

### ISSUE THREAD

**Issue by sibelius** [ptomasroos/react-native-multi-slider#46]
![image](https://user-images.githubusercontent.com/2005841/33598489-1b027142-d98a-11e7-8eca-3892b29110ca.png)

the image above has the following configs

```js
values: [100, 199]
min: 0
max: 299
```

these values are set dynamically, is this a problem?

**Comment by ptomasroos** [comment]
Interesting. Never tried it will see what we can do about it in the example app!

**Comment by sibelius** [comment]
![image](https://user-images.githubusercontent.com/2005841/33601401-3c97d79e-d993-11e7-85eb-5eb53cf981b6.png)

it looks like initial position two is kind of bug
