### ISSUE TITLE
Marker position is shifted for Snapped

### ISSUE THREAD

**Issue by jakubzaba** [ptomasroos/react-native-multi-slider#49]
When you enable `snapped`, marker is shifted by one value to the right.
It's not noticeable for high values, but totally not usable when you set max to low value e.g. `max={4}`. 

This is `<MultiSlider min={1} max={4} values={[1, 2]} />` but it shows 2 and 3 position.
<img width="349" alt="screen shot 2018-01-04 at 8 56 54 am" src="https://user-images.githubusercontent.com/1803950/34555888-60af130a-f134-11e7-8162-6bf5d14e20bf.png">

There is incorrectly calculated index in `converters.js`.
I will send PR right away.

**Comment by ptomasroos** [comment]
Thank you very much for finding this issue and sending a PR!
