### ISSUE TITLE
MultiSlider can't display completely in android

### ISSUE THREAD

**Issue by zeffon** [ptomasroos/react-native-multi-slider#5]
Hi,
Thanks for your react-native-multi-slider.
I use MultiSlider run it in my android emulator but can't display completely.
My package.json info is:
  "dependencies": {
    "babel-preset-react-native-stage-0": "*",
    "react": "^15.3.1",
    "react-native": "^0.32.0",
    "react-native-carousel": "^0.10.0",
    "react-native-form-generator": "^0.9.9",
    "react-native-multi-slider": "^0.3.5",
    "react-native-navigation": "file:../",
    "react-native-picker": "^3.0.5",
    "react-native-scrollable-tab-view": "^0.6.0",
    "react-native-slider": "^0.9.1",
    "react-native-swiper": "^1.4.11",
    "react-native-vector-icons": "^2.1.0",
    "react-redux": "^4.0.6",
    "redux": "^3.0.5",
    "redux-logger": "^2.6.1",
    "redux-thunk": "^1.0.3",
    "rn-bootstrap-buttons": "^1.0.4",
    "seamless-immutable": "^5.0.1"
  }

**Comment by ptomasroos** [comment]
Hey!

You've included the wrong npm package name.

You should be using "@ptomasroos/react-native-multi-slider": "0.0.4",

And remove the one called "react-native-multi-slider": "^0.3.5",

**Comment by sergiocloud** [comment]
I have this problem, and I have the right version.

When I use my custom marker, this isn't rendered in Android:

`
renderMarker() {
return(
			<View style={{backgroundColor: Commons.Colors.white, height: 26*initialScale, width: 26*initialScale, borderWidth: 2, borderColor: Commons.Colors.orange, borderRadius: 13*initialScale}} />
		)
	}
`

**Comment by ptomasroos** [comment]
Can you post for package.json?

**Comment by sergiocloud** [comment]
Sure:

{
  "name": "bookaffinity",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start"
  },
  "dependencies": {
    "firebase": "^3.4.1",
    "react": "15.3.2",
    "react-native": "^0.34.1",
    "react-native-autocomplete-input": "^1.1.2",
    "react-native-barcode-scanner-universal": "^1.0.5",
    "react-native-barcodescanner": "^3.1.1",
    "react-native-camera": "git+https://github.com/lwansbrough/react-native-camera.git",
    "react-native-checkbox": "^1.0.13",
    "react-native-country-picker-modal": "^0.2.7",
    "react-native-datepicker": "^1.2.2",
    "react-native-device-info": "^0.9.6",
    "react-native-drawer": "^2.2.2",
    "react-native-fbsdk": "^0.3.0",
    "react-native-fcm": "^2.5.3",
    "react-native-geocoder": "^0.4.5",
    "react-native-gifted-messenger": "^0.1.4",
    "react-native-image-picker": "^0.22.9",
    "react-native-loading-spinner-overlay": "^0.3.0",
    "react-native-maps": "^0.8.2",
    "react-native-modalbox": "^1.3.7",
    "react-native-multi-slider": "^0.3.5",
    "react-native-picker": "^4.0.2",
    "react-native-router-flux": "^3.31.2",
    "react-native-scrollable-tab-view": "^0.6.0",
    "react-native-share": "^1.0.16",
    "react-native-slider": "^0.9.1",
    "react-native-star-rating": "^1.0.5",
    "react-native-vector-icons": "^2.1.0",
    "react-redux": "^4.4.5",
    "redux": "^3.5.2",
    "redux-thunk": "^2.1.0"
  }
}

**Comment by ptomasroos** [comment]
You're using react-native-multi-slider, Thats a different package then mine. You should report this bug over at that package https://github.com/JackDanielsAndCode/react-native-multi-slider

**Comment by ptomasroos** [comment]
If you still want to use this package I would suggest you to update package.json to "@ptomasroos/react-native-multi-slider" and change your imports

**Comment by sergiocloud** [comment]
Finally I'm using your repo. Thanks!
