### ISSUE TITLE
Multiple slider

### ISSUE THREAD

**Issue by QQizi** [ptomasroos/react-native-multi-slider#53]
I have a component which use 2 different Slider.
One of the Slider is a simple one with 1 marker, the second one have 2 markers.
```
<MultiSlider
  values={[this.state.search_distance]}
  onValuesChange={this.searchDistanceValuesChange}
  trackStyle={{height:2}}
  selectedStyle={{backgroundColor: '#f77268'}}
  containerStyle={{height:20,}}
  sliderLength={_width-50}
  customMarker={CustomMarker}
  min={0}
  max={5000}
  step={1}
  allowOverlap
  snapped
/>
```

```
<MultiSlider
  values={[this.state.ageRange[0], this.state.ageRange[1]]}
  onValuesChange={this.multiSliderValuesChange}
  trackStyle={{height:2}}
  selectedStyle={{backgroundColor: '#f77268'}}
  containerStyle={{height:20,}}
  sliderLength={_width-50}
  customMarker={CustomMarker}
  min={18}
  max={99}
  step={1}
  allowOverlap
  snapped
/>
```

When i change the value of the 1 marker slider, everything is ok.
When i change the value of the 2 markers slider, the marker of the first slider move to the left of the track.

When i console.log into componentWillReceiveProps of the library, i see that both instance are called whenever a value is changed.

**Comment by ptomasroos** [comment]
Can you . please post your searchDistanceValuesChange and multiSliderValuesChange functions?

**Comment by ptomasroos** [comment]
If you run the example repo does this still happen for you ?
https://github.com/ptomasroos/react-native-multi-slider/blob/master/example/Example.js

Since if you look on the example gif this is def not the case.

**Comment by mpino88** [comment]
i have that code and i dont know why it is not showing two markers:
please help me with that
```<MultiSlider
                                isMarkersSeparated={true}
                                customMarkerLeft={(e) => {
                                return (<View><Text>{e.currentValue}</Text></View>)
                                }}

                                customMarkerRight={(e1) => {
                                return (<View><Text>{e1.currentValue}</Text></View>)
                                }}
                                onToggleOne={() => alert('check one')}
                                onToggleTwo={() => alert('check two')}
                                max={24}
                                // markerOffsetX={5}
                                // markerOffsetY={10}
                                // snapped={true}
                                minMarkerOverlapDistance={3}
                                valuePrefix={'$'}
                                valueSuffix={'#'}
                                selectedStyle={{backgroundColor:'red'}}
                                />```

**Comment by rafser01** [comment]
add values prop. Like values={[0, 10]}; 
Here 0- minimum marker value, and 10 - maximum marker value. 

Example code:
`<MultiSlider
        values={[0,10]}
        isMarkersSeparated={true}
        customMarkerLeft={(e) => (
          <View>
            <Text>{e.currentValue}</Text>
          </View>
        )}
        customMarkerRight={(e) => (<View>
            <Text>{e.currentValue}</Text>
          </View>)}
        minMarkerOverlapDistance={3}
        sliderLength={280}
      />`

@mpino88
