### ISSUE TITLE
Question about moveOne()

### ISSUE THREAD

**Issue by gudwns0102** [ptomasroos/react-native-multi-slider#54]
`moveOne = gestureState => {
    if (!this.props.enabledOne) {
      return;
    }

    var unconfined = gestureState.dx + this.state.pastOne;
    var bottom = 0;
    var trueTop = this.state.positionTwo - (this.props.allowOverlap ? 0 : this.stepLength);
    var top = trueTop === 0 ? 0 : trueTop || this.props.sliderLength;
    var confined = unconfined < bottom
      ? bottom
      : unconfined > top ? top : unconfined;`
...

` moveTwo = gestureState => {
    if (!this.props.enabledTwo) {
      return;
    }

    var unconfined = gestureState.dx + this.state.pastTwo;
    var bottom = this.state.positionOne + (this.props.allowOverlap ? 0 : this.stepLength);
    var top = this.props.sliderLength;
    var confined = unconfined < bottom
      ? bottom
      : unconfined > top ? top : unconfined;`

In the source code, why does each PanResponder calculate the boundary position in different way? Is there any significant reason that moveOne should calculate trueTop? Isn't it enough 
`var top = this.state.positionTwo - (this.props.allowOverlap ? 0 : this.stepLength); `
without trueTop, looks like more symmetric with moveTwo?

**Comment by ptomasroos** [comment]
Hey @gudwns0102 thanks for the feedback. Good question. I will try to improve this!

**Comment by gudwns0102** [comment]
I modified this part as I mentioned and guess it works well.
