### ISSUE TITLE
MultiSlider min, max and values props cannot be reset after first Mount

### ISSUE THREAD

**Issue by rtman** [ptomasroos/react-native-multi-slider#55]
Hey I have a situation where when the `MultiSlider` first mounts my max and min values are `undefined` because the system is still retrieving them. Shortly after they arrive and `componentWillReceiveProps` is triggered and the proper values set to state . The `MultiSlider` doesn't seem to react to the state change however and the markers stay at 0,0. The `Text` components showing the current range are set correctly however, but when I try to move the markers the text components change to a range of 0-0 and the right marker jumps to the far right. 

Is there something I'm doing wrong here? Can I get the markers and min/max to update properly?

My Code:
```
export class RangeMultiSlider extends React.Component{
  constructor(props){
    super(props);
    console.log('this.props', this.props)
    this.state = {
      sliderValues: [this.props.min, this.props.max],
      min: this.props.min,
      max: this.props.max
    };
  }

  onChangeValues = (values) => {
    console.log('Slider values', values)
    //console.log('this.props', this.props)
    this.setState({
      sliderValues: [values[0], values[1]]
    });
  }

  onChangeValuesFinish() {
    if (this.props.currentRefinement.min !== this.state.sliderValues[0] || this.props.currentRefinement.max !== this.state.sliderValues[1]) {
      this.props.refine({min: this.state.sliderValues[0], max: this.state.sliderValues[1]});
    }    
  }

  componentWillReceiveProps(nextProps){
    if(nextProps.min !== this.state.min && nextProps.max !== this.state.max) {
      console.log('nextProps', nextProps)
      this.setState({
        sliderValues: [nextProps.min, nextProps.max],
        min: nextProps.min,
        max: nextProps.max
      });   
    }
  }

  render(){
    console.log('sliderValues', this.state.sliderValues)
    return(
    <View style={{padding:8}}>
      <Text style={{paddingLeft: 10, fontSize: 14, color: Colors.primaryTextColor, alignSelf: 'flex-start' , textAlign: 'left'}}>
        {`${this.props.header}:`}
      </Text>
      <View style={{paddingTop: 20, paddingLeft: 8}}>
        <MultiSlider
          sliderLength={150}
          selectedStyle={{backgroundColor: Colors.mainColor}}
          unselectedStyle={{backgroundColor: 'silver'}}
          containerStyle={{height:10}}
          //trackStyle={{height:10, backgroundColor: 'red'}}
          touchDimensions={{
              height: 40,
              width: 40,
              borderRadius: 20,
              slipDisplacement: 40,
          }}
          onValuesChange={(sliderState) => this.onChangeValues(sliderState)}
          min={this.state.min}
          max={this.state.max}
          //values={[this.props.currentRefinement.min, this.props.currentRefinement.max]}
          onValuesChangeFinish={() => this.onChangeValuesFinish()}
          values={[this.state.sliderValues[0], this.state.sliderValues[1]]}
          step={1}
          customMarker={SliderMarker}/>
      </View>
      <View style={{flexDirection: 'row', justifyContent: 'space-between'}}>
        <Text style={{fontSize: 14, color: Colors.primaryTextColor, textAlign: 'left'}}>
          {this.state.sliderValues[0]}
        </Text>
        <Text style={{fontSize: 14, color: Colors.primaryTextColor , textAlign: 'right'}}>
          {this.state.sliderValues[1]}
        </Text>
      </View>
    </View>
    )
  }
}
```

Here is the console output:

```
this.props {refine: ƒ, currentRefinement: {…}, header: "Price", min: undefined, max: undefined}
sliderValues (2) [undefined, undefined]
nextProps {refine: ƒ, currentRefinement: {…}, header: "Price", min: undefined, max: undefined}
sliderValues (2) [undefined, undefined]
sliderValues (2) [undefined, undefined]
sliderValues (2) [undefined, undefined]
nextProps {refine: ƒ, currentRefinement: {…}, header: "Price", min: 7.99, max: 79.99}
sliderValues (2) [7.99, 79.99]
sliderValues (2) [7.99, 79.99]

```

**Comment by rtman** [comment]
@ptomasroos Hey can you have a look at this when you get a minute?

**Comment by ptomasroos** [comment]
I will ! Hopefully during next week @rtman sorry for keeping it hanging

**Comment by rtman** [comment]
Ok I'll try my luck on stackOverflow in the mean time as I'm trying to get this working for an app demo this week.

**Comment by ptomasroos** [comment]
Sorry to be blocking but having my own schedule for a release coming up on Friday. Have you tried this in the example app to see if the issue is reproducible there?

**Comment by ptomasroos** [comment]
I'm not really sure how the values are treated when its a float. Thats the thing I can come up with on top of my mind

**Comment by ptomasroos** [comment]
Maybe you can just handle that as display and convert it from integers instead, and increasing the range from 0-10000 to compensate or whatever fits your range

**Comment by rtman** [comment]
Thanks for helping out, part of it is a definitely the float issue. Though I'm not sure why floats would be not allowed?

Anyways, with the following change:

```
export class RangeMultiSlider extends React.Component{
  constructor(props){
    super(props);
    console.log('this.props', this.props)
    this.state = {
      sliderValues: [this.props.min, this.props.max],
      min: this.props.min,
      max: this.props.max
    };
  }

  onChangeValues = (values) => {
    console.log('Slider values', values)
    //console.log('this.props', this.props)
    this.setState({
      sliderValues: [parseInt(values[0]), parseInt(values[1])]
    });
  }

  onChangeValuesFinish() {
    if (this.props.currentRefinement.min !== this.state.sliderValues[0] || this.props.currentRefinement.max !== this.state.sliderValues[1]) {
      this.props.refine({min: this.state.sliderValues[0], max: this.state.sliderValues[1]});
    }    
  }

  componentWillReceiveProps(nextProps){
    if(nextProps.min !== this.state.min && nextProps.max !== this.state.max) {
      console.log('nextProps', nextProps)
      this.setState({
        sliderValues: [parseInt(nextProps.min), parseInt(nextProps.max)],
        min: parseInt(nextProps.min),
        max: parseInt(nextProps.max)
      });   
    }
  }

  render(){
    console.log('sliderValues', this.state.sliderValues)
    return(
    <View style={{padding:8}}>
      <Text style={{paddingLeft: 10, fontSize: 14, color: Colors.primaryTextColor, alignSelf: 'flex-start' , textAlign: 'left'}}>
        {`${this.props.header}:`}
      </Text>
      <View style={{paddingTop: 20, paddingLeft: 8}}>
        <MultiSlider
          sliderLength={150}
          selectedStyle={{backgroundColor: Colors.mainColor}}
          unselectedStyle={{backgroundColor: 'silver'}}
          containerStyle={{height:10}}
          //trackStyle={{height:10, backgroundColor: 'red'}}
          touchDimensions={{
              height: 40,
              width: 40,
              borderRadius: 20,
              slipDisplacement: 40,
          }}
          onValuesChange={(sliderState) => this.onChangeValues(sliderState)}
          min={this.state.min}
          max={this.state.max}
          //values={[this.props.currentRefinement.min, this.props.currentRefinement.max]}
          onValuesChangeFinish={() => this.onChangeValuesFinish()}
          values={[this.state.sliderValues[0], this.state.sliderValues[1]]}
          step={1}
          customMarker={SliderMarker}/>
      </View>
      <View style={{flexDirection: 'row', justifyContent: 'space-between'}}>
        <Text style={{fontSize: 14, color: Colors.primaryTextColor, textAlign: 'left'}}>
          {this.state.sliderValues[0]}
        </Text>
        <Text style={{fontSize: 14, color: Colors.primaryTextColor , textAlign: 'right'}}>
          {this.state.sliderValues[1]}
        </Text>
      </View>
    </View>
    )
  }
}
```

The markers are in the correct position when I load the component now (after receiving updated props from componentWillReceiveProps) but when I try to move any of them `onChangeValues` seems to be passing a null value for the marker and then it breaks everything. Not sure why yet. Thoughts?

**Comment by ptomasroos** [comment]
Well there has been no use of floats yet, and you can still mimic floats by making sure the range in the multislider is integers and then making sure to convert from float and back

Aka. 

You wanna support 0.00 -> 10.00
Make the slider go from 0-1000
And let 10 convert to 0.10
And 1000 to 10.00

Does that make sense as a workaround?

**Comment by rtman** [comment]
Yea for sure that workaround makes sense, maybe float support can be added at some point too.

However I'm still not sure why I'm getting a null value from the `onValuesChange` prop when moving a marker. Currently investigating ... any ideas?

**Comment by rtman** [comment]
There's issues here beyond the floating numbers.

If I set the min max props on first mount of the component to 0,50 and then try to reset min max props to 8-79 in ComponentWillReceiveProps, all of my state is correct but the component itself never seems to update. When I drag the marker all the way to the right the max number I can get to is 50, so the new min max is not applied in the component.

This explains why I was getting NaN or null values before, because in my use case the min and max are set to undefined on first loading of the component and then to parseInt(7.99) and parseInt(79.99) when the range is retrieved from the server and componentWillReceiveProps is triggered. If I move the marker it immediately goes to NaN/null and breaks. 

So this component doesn't seem to listen for min/max updates after the first mount, can this be fixed?

**Comment by rtman** [comment]
I found the issue and have submitted this [PR:56](https://github.com/ptomasroos/react-native-multi-slider/pull/56) please have a look and let me know if its ok for you.

**Comment by ptomasroos** [comment]
Thank you very much. Will check it out tomorrow!

**Comment by rtman** [comment]
Np thanks for making this component!

**Comment by ptomasroos** [comment]
Closed because of https://github.com/ptomasroos/react-native-multi-slider/pull/56#issuecomment-361587954
