### ISSUE TITLE
Example doesn't work

### ISSUE THREAD

**Issue by skv-headless** [ptomasroos/react-native-multi-slider#6]
but it work if import ```ptomasroos/react-native-multi-slider``` here https://github.com/ptomasroos/react-native-multi-slider/blob/master/example/Example.js#L14

**Comment by skv-headless** [comment]
![1480066711458](https://cloud.githubusercontent.com/assets/1488195/20620753/af2b440e-b314-11e6-8cc7-9870137ff943.jpg)

**Comment by ptomasroos** [comment]
Did you npm install in the example/Example as well? Since it moves the lib files over there.

**Comment by skv-headless** [comment]
Yes. Npm 3. Node 7

**Comment by ptomasroos** [comment]
Thanks! I've fixed the example now!
