### ISSUE TITLE
how can set size for custom marker ?

### ISSUE THREAD

**Issue by lytrunghieu** [ptomasroos/react-native-multi-slider#61]
I had try set width for custom Marker, but not working, it is util keep old size
![screen shot 2018-02-22 at 5 37 12 pm](https://user-images.githubusercontent.com/24516706/36533727-1127f1a0-17f7-11e8-9b00-496546582f84.png)

**Comment by ptomasroos** [comment]
Can you please create a example repo based on the example I've got in this repo. And I'll happily help you out!

**Comment by ptomasroos** [comment]
Will close since no response for a month
