### ISSUE TITLE
New npm release

### ISSUE THREAD

**Issue by philjoseph** [ptomasroos/react-native-multi-slider#62]
Hello @ptomasroos - It seems that the last npm release is from Aug 17, while many commits came in the past months. 
When using the npm latest (0.3.6) I am getting code that break with react 16 and react-native .53. Especially in `node_modules/react-native-multi-slider/mockProps.js` I have 
    'use strict';

    var React = require('react');
    var ReactNative = require('react-native');
    var {
      PropTypes // ====> break with react 16
    } = React;

Shall we take the latest in master branch rather than the npm latest version ? Any plan to issue a new version in npm ?

Tactac

**Comment by ptomasroos** [comment]
0.0.12 is the latest release. 

You’re probably using another library. Feel free to read the readme how to install. 

https://www.npmjs.com/package/@ptomasroos/react-native-multi-slider

**Comment by philjoseph** [comment]
You're right. I got confused since both your and https://github.com/JackDanielsAndCode/react-native-multi-slider have the exact same name and provides very similar functionality. Any connection between the two projects?

**Comment by ptomasroos** [comment]
No not really mine supports android and is up to date.
