### ISSUE TITLE
Markers override each other

### ISSUE THREAD

**Issue by sarykemmoun** [ptomasroos/react-native-multi-slider#63]
Hello.
first, thanks for the very useful library.
I have a little problem: when the markers are too close it overrides each other
![screenshot from 2018-03-11 10-44-36](https://user-images.githubusercontent.com/28590349/37251644-a921f53c-251c-11e8-93f1-789e48aa86ca.png)
Do you have any solution? thanks.

**Comment by ptomasroos** [comment]
What do you think the behavior should be like instead?

**Comment by sarykemmoun** [comment]
That the smallest gap (as the last attachment, 13:00 - 13:15 when the step size is 15 mins) will seem like this: 
![screenshot from 2018-03-11 12-04-18](https://user-images.githubusercontent.com/28590349/37252114-5ff2f462-2524-11e8-8790-415cfb0f6b53.png)

**Comment by AFMW** [comment]
Hello, @ptomasroos  .
Is this solved now?

**Comment by dyihoon90** [comment]
my team faced this too and I've created a PR in #112
