### ISSUE TITLE
error: positionOne is not defined

### ISSUE THREAD

**Issue by alexfoxy** [ptomasroos/react-native-multi-slider#66]
Hey,

I'm getting an error using your plugin:

<img width="319" alt="screen shot 2018-04-11 at 11 49 46" src="https://user-images.githubusercontent.com/151772/38612427-95bd2a46-3d7e-11e8-98e5-3ed5aaef15ab.png">

Looking at the code, shouldn't line 152 of MultiSlider.js be:
`var positionOne = valueToPosition(...`
not 
`positionOne = valueToPosition(...`

Same goes for positionTwo - line 161.

Doing this fixes my errors.

**Comment by ptomasroos** [comment]
Can you please send a pr?

**Comment by alexfoxy** [comment]
Done
