### ISSUE TITLE
Example doesn't work in my shiny new xcode 8

### ISSUE THREAD

**Issue by skv-headless** [ptomasroos/react-native-multi-slider#7]
react-native version is to old. update it?

**Comment by skv-headless** [comment]
![1480066942008](https://cloud.githubusercontent.com/assets/1488195/20620810/02f63d14-b315-11e6-8e28-40f6c8e2792b.jpg)

**Comment by ptomasroos** [comment]
Yup! do it

**Comment by ptomasroos** [comment]
Upgraded project files to RN 0.38 now. Works fine on Xcode 8
