### ISSUE TITLE
Less Detail Documentation

### ISSUE THREAD

**Issue by blackinitial** [ptomasroos/react-native-multi-slider#72]
- [x] I have searched [existing issues](https://github.com/ptomasroos/react-native-multi-slider/issues)
- [x] I am using the [latest multi slider version](https://www.npmjs.com/package/@ptomasroos/react-native-multi-slider)

I am new in react native and i haven't used slider. I have read doc but unknown api to use. i have comparison with api slider rn official and issues post but its different.

thanks

**Comment by ptomasroos** [comment]
Can you please give a example where it’s causing a error?
