### ISSUE TITLE
RTL - Touch is reversed

### ISSUE THREAD

**Issue by amitassaraf** [ptomasroos/react-native-multi-slider#73]
Hey,

I am using the latest version of the react-native-multi-slider on an RTL app.
When testing and using I18nManager.forceRTL(true) the slider looks to function correctly until you try and move one of the markers.

What happens is that if you slide your finger right, the marker goes left. If you slide your finger left, the marker goes right.

I have managed to reproduce this issue on a clean project (iOS + Android).

I searched a bit here and saw that there was a PR for RTL support. I didn't have much time to read the changes but it seems it doesn't work / it stopped working.

Would love if this could be fixed!

Best,
Amit

**Comment by ptomasroos** [comment]
The rtl has not been released yet. Will do that later today if you need it.

**Comment by amitassaraf** [comment]
@ptomasroos I'd love it if you can release it, or at least upload it to a branch and ill download it and publish it for personal use under an alias :)

Thanks!

**Comment by ptomasroos** [comment]
I will release it tomorrow morning. Sorry for delay!

**Comment by Abakrii** [comment]
@ptomasroos  still not working!
