### ISSUE TITLE
Using native sliders to make range slider

### ISSUE THREAD

**Issue by Noitidart** [ptomasroos/react-native-multi-slider#76]
I am trying to make a range slider using the native `<Slider>` component.  My goal is native perf and perfect native look.

My goal is to on press down, it should grab the slider that the press it is closest to. I have been trying for about a day with various stuff but can't figure it out.

I created a snack here: https://snack.expo.io/@noitsnack/rangeslider-cannot-move-one-in-back

I was wondering if you wanted to help me pursue this idea. I'm close but not quit there.

Here is a screenshot, the dot on the left is the slider in the back. I position the sliders on top of each other by using `position: 'absolute'`.

It leads to some issues, like not being able to slide the one underneath. And preventing overlap is another.

![](https://i.imgur.com/cu3ezWl.png)

**Comment by ptomasroos** [comment]
Since this issue isn't about the MultiSlider I'm sorry we're out of time to help out with side projects, thanks for reaching out though!
