### ISSUE TITLE
Create label `good first issue` for first time contributors?

### ISSUE THREAD

**Issue by dammy95** [ptomasroos/react-native-multi-slider#79]
Would like to contribute to this project but found no label/tag about which issues might be good for first timers. Can a `good first issue` label be created and the Issues labelled accordingly? Thanks! 😄

**Comment by ptomasroos** [comment]
Hey @dammy95 ! Thanks, will try clean up the issues and see what could be doable 👍

**Comment by dammy95** [comment]
Thanks! @ptomasroos 😄

**Comment by ptomasroos** [comment]
I've now marked up good first issues, which are mainly around styling and simpler implementations rather then the logic around drag, positioning ect. Feel free to take a bite and if you need any help let me know @dammy95
