### ISSUE TITLE
Is it possible to change values programmatically?

### ISSUE THREAD

**Issue by ngytc** [ptomasroos/react-native-multi-slider#80]
- [x] I have searched [existing issues](https://github.com/ptomasroos/react-native-multi-slider/issues)
- [x] I am using the [latest multi slider version](https://www.npmjs.com/package/@ptomasroos/react-native-multi-slider)

This is not a bug report but a question regarding to features.
I am currently using MultiSlider in a screen for users to setting ranges. In this screen there is a Reset Button, when pressed, MultiSlider should reset to it's default values. I couldn't find a method to change values of MultiSlider programmatically? Is this possible? Thanks!

**Comment by ptomasroos** [comment]
https://github.com/ptomasroos/react-native-multi-slider/blob/master/example/Example.js#L72

**Comment by chrismang** [comment]
Can I change one value depending on the change of the other? I want to control a video timmer of 1 minute, and I want to set the difference between the markers in 60 seconds. Is it possible to do that? I tried using your suggestion but is not working as I expected

**Comment by jcohenho** [comment]
> https://github.com/ptomasroos/react-native-multi-slider/blob/master/example/Example.js#L72

This link no longer works, do you have another example of resetting functionality?

**Comment by dytra** [comment]
> https://github.com/ptomasroos/react-native-multi-slider/blob/master/example/Example.js#L72

not found

**Comment by erickcrus** [comment]
If you want to reset slider state, you can use a ref value, and set slider state as follow:
```
const slider = useRef();

const resetSlider = () => {
      if( slider.current ) slider.current.setState({ positionOne:0, onePressed:false, pastOne:0 });
}

return <View>
      <MultiSlider ref={ slider } {...props} />
      <Button onPress={ resetSlider } text="Reset slider" />
</View>
```
