### ISSUE TITLE
returning index position instead of returning value

### ISSUE THREAD

**Issue by rjoydip** [ptomasroos/react-native-multi-slider#84]
- [X] I have searched [existing issues](https://github.com/ptomasroos/react-native-multi-slider/issues)
- [X] I am using the [latest multi slider version](https://www.npmjs.com/package/@ptomasroos/react-native-multi-slider)

## Steps to Reproduce

```js
multiSliderValuesChange = (values) => {
 console.log(values); // output: [0, 10]
}

<MultiSlider values={[6, 24]} onValuesChange={this.multiSliderValuesChange} step={1} />
```

## Expected Behavior

Should return the actual value of the step in `onChange` method.

## Actual Behavior

`MultiSlider` onChange returning index position instead of returning value.

**Comment by ptomasroos** [comment]
I think you forgot to read the instructions in the ISSUE_TEMPLATE, can you please provide me with a reproduction example and I will take a look. We use this in our app and its returning the values since we have a age range from 18-65. Have you tried changing your values={[0, 24]} to values={[20, 50]} ?

**Comment by rjoydip** [comment]
Actually, I read the ISSUE_TEMPLATE but it was hard for me to extract my slider code from my application. Let me try to reproduce an example.

> have a age range from 18-65. Have you tried changing your values={[0, 24]} to values={[20, 50]} ?
No, I haven't. I will check that too.

Please keep this issue opened for some time.

**Comment by ptomasroos** [comment]
If you can't extract it which has the application code which causes the error imaging how hard it will be for me for even guessing the bug or error :-)

**Comment by rjoydip** [comment]
@ptomasroos Here is my code sample https://snack.expo.io/ryqxHQdIX
If you change `state` value `[6, 24] to [3, 7]` then you could understand

**Comment by ptomasroos** [comment]
Thanks! Will check this out now

**Comment by ptomasroos** [comment]
So you've not added any min + max in this range which causes this most likely to be quite some strange behaviour. 

If you add 
```
          step={1}
          min={0}
          max={65}
```
