### ISSUE TITLE
'RCTRootView.h' file not found

### ISSUE THREAD

**Issue by KingAmo** [ptomasroos/react-native-multi-slider#85]
- [x] I have searched [existing issues](https://github.com/ptomasroos/react-native-multi-slider/issues)
- [x] I am using the [latest multi slider version](https://www.npmjs.com/package/@ptomasroos/react-native-multi-slider)

it is ok in android , but get this error in iOS
![2018-08-15 16 34 18](https://user-images.githubusercontent.com/29938227/44139256-19286c46-a0a9-11e8-8cd3-19f0d274fef8.png)

## Steps to Reproduce

npm install --save `@ptomasroos/react-native-multi-slider`
react-native link
react-native run-ios

**Comment by ptomasroos** [comment]
The react-native-multi-slider has nothing todo with native code and is written in pure JS so this error sadly does not belong to multi-slider

**Comment by KingAmo** [comment]
> The react-native-multi-slider has nothing todo with native code and is written in pure JS so this error sadly does not belong to multi-slider

it do belong to multi-slider...the error occur in Slider.xcodeproj/Slider/appDelegate.m
![image](https://user-images.githubusercontent.com/29938227/46133326-cad7ca00-c272-11e8-9074-85f7c1c7a65b.png)

**Comment by ptomasroos** [comment]
Now, i do not know what kind of libraries you've implemented in your React-native app since I haven't seen any source code.

But can you please show me where Slider.xcodeproj can be found in my slider implementation? https://github.com/ptomasroos/react-native-multi-slider/

**Comment by KingAmo** [comment]
oh..sorry, you mean Slider.xcodeproj does not below to multi-slider? i try delete it and then build success... hahaha, thanks a lot..
