### ISSUE TITLE
Can we change color of the slider button / handle?

### ISSUE THREAD

**Issue by harrydry2** [ptomasroos/react-native-multi-slider#86]
I know we can change color of slider using: 

selectedStyle={{}} and 
unselectedStyle={{}}

but I can't seem to chang the color for the actual handle / button which you use to drag the slider. I know I can load a custom Image but is there a simpler way to do this? 

Many thanks. Love the project! 💯

**Comment by ptomasroos** [comment]
You can pass in markerStyle and it will respect that
