### ISSUE TITLE
Custom sliders

### ISSUE THREAD

**Issue by GajendraFork** [ptomasroos/react-native-multi-slider#87]
- [yes] I have searched [existing issues](https://github.com/ptomasroos/react-native-multi-slider/issues)
- [yes] I am using the [latest multi slider version](https://www.npmjs.com/package/@ptomasroos/react-native-multi-slider)

**Comment by GajendraFork** [comment]
Cant draw different markers for a multislider

**Comment by ptomasroos** [comment]
I'm missing a expo link for this issue. Please attach it

**Comment by GajendraFork** [comment]
haven't tried anything. I just cant make out how can i have different custom markers in multislider.?

**Comment by ptomasroos** [comment]
Feel free to check the examples/Basic and run it, its very clear how to implement a Custom Marker.
