### ISSUE TITLE
Can it be integrated with redux-form?

### ISSUE THREAD

**Issue by salvagit** [ptomasroos/react-native-multi-slider#89]
- [x] I have searched [existing issues](https://github.com/ptomasroos/react-native-multi-slider/issues)
- [x] I am using the [latest multi slider version](https://www.npmjs.com/package/@ptomasroos/react-native-multi-slider)

## Steps to Reproduce

I'm trying to integrate it into a field of redux-form as follows,
```javascript
<Field
    name = 'age'
    component = { MultiSlider }
    values = { this.state.multiSliderValue }
    multiSliderValuesChange={ values => this.multiSliderValuesChange(values) }          min={18}
    max={80}
    step={1}
/>
```

My MultiSlider Component,

```javascript
export default ({
  placeholder, label,
  values, multiSliderValuesChange, min, max, step,
  input, meta: { touched, error, valid },
  ...inputProps }) =>
  <View>
    <Item
      success={touched && (undefined === error)}
      error={touched && (undefined !== error)}
    >
      <MultiSlider
        {...inputProps}
        onValuesChange = { values => multiSliderValuesChange(values) }
        placeholder = { placeholder || label }
        values = { values }
        sliderLength={280}
        min={min}
        max={max}
        step={step}
        allowOverlap
        snapped
      />

      {
        touched && (!error && valid ?
          <Icon name='checkmark-circle' />
          :
          <Icon name='close-circle' />)
      }

    </Item>
    {
      touched && (error &&
        <Text style={{ color: 'red' }}>{error}</Text>)
    }
  </View>
```

## Expected Behavior

but by submitting the form I do not get the age value

## Actual Behavior

but by submitting the form I do not get the age value.

Am I passing some value incorrectly or do I need to pass some?
thank you very much!

**Comment by ptomasroos** [comment]
Hi! 

If you could create a expo.io out of this, I'm pretty sure I will be able to help you out.

Me myself haven't used redux-form so can't really tell but since it seems to be very generic I dont see why it wouldn't work.

**Comment by salvagit** [comment]
thank you very much I will soon generate an expo.io and I'll share it with you. thanks again.

**Comment by salvagit** [comment]
How are you ? I leave a link to the expo,

https://snack.expo.io/@salvagit/redux-form-multislider-example?session_id=snack-session-rJSHmEwtQ

thank you very much.

**Comment by ptomasroos** [comment]
This is totally a redux-form thing and I'm no expert by I think I got it running to the point you've wanted. But at least you will probably succeed from here.

https://snack.expo.io/@ptomasroos/redux-form-multislider-example

**Comment by salvagit** [comment]
it worked! thank you very much!
