### ISSUE TITLE
Android Issue

### ISSUE THREAD

**Issue by namburirajesh** [ptomasroos/react-native-multi-slider#90]
## Steps to Reproduce
 1. Above code working fine on IOS , but when coming to Android , if I drag the slider to intial value (0) and again moving to greater position >0 , track one is becoming transperant 

## Expected Behavior
  Track color should be displayed

## Actual Behavior
Track color should be displayed

Image when slider is at position 0
![image](https://user-images.githubusercontent.com/14882184/46403588-8cce2080-c720-11e8-8a19-1f4877a789ba.png)

Image when slider is at position >0
![image](https://user-images.githubusercontent.com/14882184/46403605-99eb0f80-c720-11e8-8e12-901cd51d3174.png)

**Comment by ptomasroos** [comment]
Will close because you did not follow the issue template.

Please read the instructions again and open a new issue to get help.
