### ISSUE TITLE
is it possible to have specific values

### ISSUE THREAD

**Issue by sibelius** [ptomasroos/react-native-multi-slider#97]
- [x] I have searched [existing issues](https://github.com/ptomasroos/react-native-multi-slider/issues)
- [x] I am using the latest [latest multi slider version](https://www.npmjs.com/package/@ptomasroos/react-native-multi-slider)

I'd like to keep scrolling positions in specific positions.
For instance, if I have min={1} and max={3}, I'd like to divide the slider in 3 positions to keep the position indicator, if the user stop scrolling in another position in slider, it should take the indicator to one of the 3 positions 

## Steps to Reproduce

Create a simple slider where min={1} and max={3}

## Expected Behavior

it should only allow indicators in 3 fixed positions

## Actual Behavior

it accept more positions on slider for the same value

**Comment by ptomasroos** [comment]
Try snapped={true}

**Comment by sibelius** [comment]
it works tks, I've sent a PR to improve the docs
